baseURL = "http://www.thearchive.nz"
title = "The Archive"
theme = "hugo-coder"
languageCode = "en"
defaultContentLanguage = "en"
paginate = 20
enableEmoji = true
enableRobotsTXT = true
# Enable Disqus comments

[markup.highlight]
noClasses = false

[params]
author = "Nathan Cobbald"
description = ""
keywords = "blog,developer,personal,cyber,cybersecurity,hugo,nathan,cobbald,portfolio,nathan cobbald"
info = ["Penetration Tester", "Cyber Security", "Software Development"]
avatarURL = "images/glowingmushroom.jpg"
favicon = "favicon.ico"
dateFormat = "January 2, 2006"
since = 2023
# Git Commit in Footer, uncomment the line below to enable it
commit = "https://github.com/luizdepra/hugo-coder/tree/"
# Right To Left, shift content direction for languagues such as Arabic
rtl = false
# Specify light/dark colorscheme
colorScheme = "auto"
# Hide the toggle button, along with the associated vertical divider
hideColorSchemeToggle = false
# Series see also post count
maxSeeAlsoItems = 5
# Custom CSS
customCSS = []
# Custom SCSS, file path is relative to Hugo's asset folder (default: {your project root}/assets)
customSCSS = []

# Custom JS
customJS = []

# Custom remote JS files
customRemoteJS = []

#If you want to use goatcounter(https://goatcounter.com) for analytics, add this section
[params.goatCounter]
code = "thearchive"

[taxonomies]
category = "categories"
series = "series"
tag = "tags"
author = "authors"

[[params.social]]
name = "Github"
icon = "fa fa-2x fa-github"
weight = 1
url = "https://github.com/Real4XoR/"

[[params.social]]
name = "LinkedIn"
icon = "fa fa-2x fa-linkedin"
weight = 4
url = "https://www.linkedin.com/in/nathan-cobbald-106b4a253/"

[languages.en]
languageName = ":uk:"

[[languages.en.menu.main]]
name = "About"
weight = 1
url = "about/"

[[languages.en.menu.main]]
name = "Posts"
weight = 2
url = "posts/"

[[languages.en.menu.main]]
name = "Projects"
weight = 3
url = "projects/"

[[languages.en.menu.main]]
name = "Contact"
weight = 5
url = "contact/"
