[build]
publish = "public"
command = "hugo --gc --minify"

[build.environment]
HUGO_VERSION = "0.111.3"
HUGO_THEME = "repo"

[context.deploy-preview]
command = "hugo --gc --minify --enableGitInfo"

[context.production.envitonment]
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

