[build]
publish = "public"
command = "hugo"

[build.environment]
HUGO_VERSION = "0.111.3"

[context.deploy-preview]
command = "hugo --enableGitInfo"

[context.production.envitonment]
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

